<template>
  <section class="texture overflow-hidden">
    <div class="mx-auto grid max-w-6xl items-center gap-10 px-5 pb-20 pt-16 md:grid-cols-[1.1fr_.9fr] md:pb-28 md:pt-24">
      <div class="fade-up"><p class="mb-5 text-xs font-bold uppercase tracking-[.3em] text-tomato">Massas artesanais congeladas</p><h1 class="display max-w-xl text-6xl font-bold leading-[.95] text-forest md:text-8xl">O sabor de uma mesa bem cuidada.</h1><p class="mt-7 max-w-md text-lg leading-relaxed text-ink/70">Receitas de família, ingredientes de verdade e praticidade para o seu momento especial.</p><div class="mt-8 flex flex-wrap gap-3"><NuxtLink to="/cardapio" class="rounded-full bg-tomato px-6 py-3 font-bold text-white hover:bg-forest">Ver cardápio</NuxtLink><NuxtLink to="/informacoes" class="rounded-full border border-forest px-6 py-3 font-bold text-forest hover:bg-forest hover:text-white">Como funciona</NuxtLink></div></div>
      <div class="relative flex min-h-[360px] items-center justify-center rounded-[3rem] bg-forest p-10 text-center text-cream"><div class="absolute -right-10 -top-10 h-32 w-32 rounded-full border-[18px] border-gold/80"></div><div class="absolute -bottom-8 -left-8 h-24 w-24 rounded-full bg-tomato"></div><div class="relative"><p class="display text-7xl font-bold">feito</p><p class="text-5xl font-bold italic text-gold">à mão</p><p class="mt-6 text-sm uppercase tracking-[.25em] text-cream/70">para a sua casa</p></div></div>
    </div>
  </section>
  <section class="mx-auto max-w-6xl px-5 py-16"><div class="grid gap-8 border-y border-forest/15 py-10 sm:grid-cols-3"><div><p class="display text-3xl font-bold text-tomato">11</p><p class="mt-1 text-sm text-ink/60">famílias de massas</p></div><div><p class="display text-3xl font-bold text-tomato">2 dias</p><p class="mt-1 text-sm text-ink/60">de antecedência</p></div><div><p class="display text-3xl font-bold text-tomato">100%</p><p class="mt-1 text-sm text-ink/60">carinho em cada receita</p></div></div><div class="mt-14 flex flex-col items-start justify-between gap-5 sm:flex-row sm:items-end"><div><p class="text-xs font-bold uppercase tracking-[.25em] text-tomato">Para hoje</p><h2 class="display mt-2 text-4xl font-bold text-forest">Escolha sua massa.</h2></div><NuxtLink to="/cardapio" class="font-bold text-forest underline decoration-tomato decoration-2 underline-offset-4">Explorar o cardápio →</NuxtLink></div></section>
</template>
